import DomChainer from "../dist/index.js";

DomChainer.id("description")
	.addClass("add1")
	.addClass("add2 add3")
	.addClass("add4", "add5")
	.addClass("add6", "add7 add8")
	.removeClass("remove1")
	.removeClass("remove2 remove3")
	.removeClass("remove4", "remove5")
	.removeClass("remove6", "remove7 remove8")
	.toggleClass("toggle1")
	.toggleClass("toggle2")
	.toggleClass("toggle3")
	.toggleClass("toggle4")
	.toggleClass("toggle1")
	.toggleClass("toggle3", false)
	.toggleClass("toggle4", true)
	.if(false)
	.addClass("should-not-be-added")
	.else()
	.addClass("should-be-added")
	.end()
	.addClass("final");
