/* eslint-disable no-console */
DomChainer.id("description")
	.addClass("add1")
	.addClass("add2 add3")
	.addClass("add4", "add5")
	.addClass("add6", "add7 add8")
	.tap((el) => console.log(el.classList.value))
	.removeClass("add1")
	.removeClass("add2 add3")
	.removeClass("add4", "add5")
	.removeClass("add6", "add7 add8")
	.tap((el) => console.log(el.classList.value))
	.toggleClass("toggle1")
	.toggleClass("toggle2")
	.toggleClass("toggle3")
	.toggleClass("toggle4")
	.toggleClass("toggle1")
	.toggleClass("toggle3", false)
	.toggleClass("toggle4", true)
	.tap((el) => console.log(el.classList.value))
	.removeClass("toggle2", "toggle4")
	.if(false)
	.addClass("should-not-be-added")
	.else()
	.addClass("should-be-added")
	.end()
	.addClass("final")
	.tap((el) => console.log(el.classList.value));
